apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-canary
  labels:
    app: flask
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: canary
  template:
    metadata:
      labels:
        app: flask
        version: canary
      annotations:
        sidecar.istio.io/inject: "true"  # Enable Istio sidecar injection
    spec:
      containers:
        - name: flask
          image: sukanya996/canary-deploy:canary-$(BUILD_NUMBER)
          ports:
            - containerPort: 5000
